on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install additonal system dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgdal-dev libgeos-dev libproj-dev python3-gdal

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
